### ISSUE TITLE
Issue on signin

### ISSUE THREAD

**Issue by GeoffBH** [rcdevs/openotp_authentication_owncloud#1]
When I sign in to Owncloud v10.2.0 and use the OpenOTP plugin, I get this error in /var/www/owncloud/data/owncloud.log on sign-in:

{"reqId":"wQag8sAvYvAwY39cwIp1","level":3,"time":"2020-09-22T19:40:21+00:00","remoteAddr":"IPADDRESS","user":"USERNAME","app":"PHP","method":"POST","url":"\/index.php\/login\/challenge\/rcdevsopenotp","message":"O**bject of class OC\\User\\User could not be converted to string at \/var\/www\/owncloud\/apps\/twofactor_rcdevsopenotp\/lib\/Provider\/TwoFactorRCDevsOpenOTPProvider.php#346**"}

The app works as expected though, other than this error.

I understand the plugin has not been updated in some time, probably due to no one reporting any issues, thus this report.

Thank you for investigating.

**Comment by rcdevscare** [comment]
Thank you for your Suggestion. We will fix this in next few days.

**Comment by rcdevs** [comment]
Fixed in the upcoming release 1.2.3 that will bring compatibility with Owncloud 10.8.0
